import { CurriculumGraphSchema } from "./contracts";

export const museionFoundations = CurriculumGraphSchema.parse({
  schemaVersion: "1.0",
  id: "museion-foundations",
  title: "Museion foundations",
  nodes: [
    { id: "negative-numbers", title: "Working with Negative Numbers", subject: "Arithmetic", level: "foundation", lessonId: "negative-numbers", prerequisiteIds: [], objective: "Reason about signed quantities and operations on the number line.", provenance: { kind: "museion-authored", label: "Museion authored lesson", url: null } },
    { id: "order-of-operations", title: "Order of Operations", subject: "Arithmetic", level: "foundation", lessonId: "order-of-operations", prerequisiteIds: [], objective: "Apply operation precedence and explain each grouping decision.", provenance: { kind: "museion-authored", label: "Museion authored lesson", url: null } },
    { id: "fractions-unlike-denominators", title: "Unlike Denominators", subject: "Arithmetic", level: "developing", lessonId: "fractions-unlike-denominators", prerequisiteIds: ["order-of-operations"], objective: "Build equivalent fractions before combining quantities.", provenance: { kind: "museion-authored", label: "Museion authored lesson", url: null } },
    { id: "linear-equations-intro", title: "Solving Linear Equations", subject: "Algebra", level: "developing", lessonId: "linear-equations-intro", prerequisiteIds: ["negative-numbers", "order-of-operations"], objective: "Preserve equality while isolating an unknown.", provenance: { kind: "museion-authored", label: "Museion authored lesson", url: null } },
    { id: "binary-numbers", title: "Binary Numbers", subject: "Computer Science", level: "extension", lessonId: "binary-numbers", prerequisiteIds: ["order-of-operations"], objective: "Connect positional notation to powers of two.", provenance: { kind: "museion-authored", label: "Museion authored lesson", url: null } },
    { id: "algebra-balance-equality-as-invariant", title: "Equality as an Invariant", subject: "Algebra", level: "developing", lessonId: "algebra-balance-equality-as-invariant", prerequisiteIds: ["negative-numbers", "order-of-operations"], objective: "Read equality as a relation and audit whether a move preserves it.", provenance: { kind: "museion-authored", label: "Museion authored course lesson", url: null } },
    { id: "algebra-balance-inverse-operations-and-isolation", title: "Inverse Operations and Isolation", subject: "Algebra", level: "developing", lessonId: "algebra-balance-inverse-operations-and-isolation", prerequisiteIds: ["algebra-balance-equality-as-invariant"], objective: "Use inverse operations on both sides to isolate an unknown.", provenance: { kind: "museion-authored", label: "Museion authored course lesson", url: null } },
    { id: "algebra-balance-two-step-equations-and-transfer", title: "Two-Step Equations and Transfer", subject: "Algebra", level: "developing", lessonId: "algebra-balance-two-step-equations-and-transfer", prerequisiteIds: ["algebra-balance-inverse-operations-and-isolation"], objective: "Plan, solve, and verify two-step equations in nearby contexts.", provenance: { kind: "museion-authored", label: "Museion authored course lesson", url: null } },
    { id: "sorted-search-space", title: "Prepare a Search Space", subject: "Computer Science", level: "developing", lessonId: "sorted-search-space", prerequisiteIds: [], objective: "Check the ordering contract and identify the candidate interval.", provenance: { kind: "museion-authored", label: "Museion authored course lesson", url: null } },
    { id: "binary-search-invariant", title: "Keep the Target in the Interval", subject: "Computer Science", level: "developing", lessonId: "binary-search-invariant", prerequisiteIds: ["sorted-search-space"], objective: "Maintain inclusive bounds without discarding a possible target.", provenance: { kind: "museion-authored", label: "Museion authored course lesson", url: null } },
    { id: "logarithmic-reasoning-and-transfer", title: "Reason About Repeated Halving", subject: "Computer Science", level: "extension", lessonId: "logarithmic-reasoning-and-transfer", prerequisiteIds: ["binary-search-invariant"], objective: "Reason about repeated halving without turning asymptotics into timing claims.", provenance: { kind: "museion-authored", label: "Museion authored course lesson", url: null } },
  ],
});
