import type { Metadata } from "next";
import Link from "next/link";
import MaiaCharacter from "@/components/MaiaCharacter";
import { buildDashboardSnapshot } from "@/lib/dashboard";
import { buildRevisitPlan, formatDueDate, REVISIT_INTERVALS_DAYS } from "@/lib/revisit/scheduler";
import { readLearnerId } from "@/lib/server/learner";

export const metadata: Metadata = { title: "Review", description: "A spaced review queue computed from recorded learning signals." };
export const dynamic = "force-dynamic";

function titleCase(value: string) {
  return value.replaceAll("-", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
}

export default async function ReviewPage() {
  const learnerId = await readLearnerId();
  const snapshot = await buildDashboardSnapshot(learnerId ?? "new-learner");
  const scheduled = buildRevisitPlan(learnerId ?? "new-learner").filter((item) => item.status === "scheduled");
  return <div className="mx-auto w-full max-w-6xl px-4 py-8 sm:px-6 lg:px-8 lg:py-10"><header className="grid gap-5 border-b border-ink/10 pb-7 md:grid-cols-[1fr_auto] md:items-end"><div><p className="text-sm font-medium text-lapis-dark">Review</p><h1 className="mt-2 title-page">Revisit what the record can justify.</h1><p className="mt-3 max-w-2xl leading-7 text-ink-soft">Due items come from registered misconceptions, assisted completions, and the spaced schedule — an expanding ladder computed from recorded timestamps, never invented.</p></div><span className="rounded-full bg-surface px-4 py-2 text-sm font-medium text-ink-soft">{snapshot.reviewQueue.length} ready</span></header>
    <div className="mt-7 grid gap-6 lg:grid-cols-[minmax(0,1.25fr)_minmax(18rem,.75fr)]"><div className="min-w-0 space-y-8"><section aria-labelledby="queue-title"><h2 id="queue-title" className="text-xl font-semibold">Due now</h2>{snapshot.reviewQueue.length ? <ol className="mt-4 space-y-3">{snapshot.reviewQueue.map((item, index) => <li key={item.id}><Link href={item.href} className="grid gap-4 rounded-2xl border border-ink/10 bg-surface p-5 shadow-[var(--shadow-tight)] transition hover:-translate-y-0.5 hover:border-lapis/30 sm:grid-cols-[2.25rem_1fr_auto] sm:items-center"><span className={`grid h-9 w-9 place-items-center rounded-xl text-sm font-semibold tabular-nums ${item.priority === "high" ? "bg-gold-soft text-ink" : "bg-paper"}`}>{index + 1}</span><span><span className="block font-semibold">{item.concept}</span><span className="mt-1 block text-sm leading-5 text-ink-soft">{item.reason}</span></span><span className="text-sm font-semibold text-lapis-dark">Review →</span></Link></li>)}</ol> : <div className="mt-4 flex flex-wrap items-center gap-6 rounded-2xl border border-dashed border-ink/15 bg-surface p-7"><MaiaCharacter state="curious" className="h-16 w-14 shrink-0" title="Maia, waiting for checked work" /><div className="min-w-0 flex-1"><h3 className="font-semibold">No review signal yet.</h3><p className="mt-2 text-sm leading-6 text-ink-soft">Complete checked work first. Your queue will stay empty rather than guessing.</p><Link href="/library" className="mt-5 inline-flex rounded-lg bg-ink px-4 py-2.5 text-sm font-semibold text-white">Choose a lesson</Link></div></div>}</section>
      {scheduled.length > 0 && <section aria-labelledby="scheduled-title"><h2 id="scheduled-title" className="text-xl font-semibold">Scheduled</h2><p className="mt-1 text-sm text-ink-soft">Verified concepts waiting for their next unassisted check.</p><ol className="mt-4 space-y-2">{scheduled.map((item) => <li key={item.concept} className="flex flex-wrap items-center gap-3 rounded-xl border border-ink/8 bg-surface/70 px-4 py-3"><span className="min-w-0 flex-1"><span className="block text-sm font-semibold">{titleCase(item.concept)}</span><span className="mt-0.5 block text-xs text-ink-soft">{item.lessonTitle}</span></span><span aria-label={`Ladder rung ${item.rung + 1} of ${REVISIT_INTERVALS_DAYS.length}`} className="flex items-center gap-1">{REVISIT_INTERVALS_DAYS.map((interval, index) => <span key={interval} aria-hidden="true" className={`h-1.5 w-4 rounded-full ${index <= item.rung ? "bg-correct" : "bg-ink/10"}`} />)}</span><span className="shrink-0 rounded-full bg-paper px-2.5 py-1 text-xs font-medium tabular-nums text-ink-soft">{formatDueDate(item.dueAt)}</span></li>)}</ol></section>}</div>
      <aside className="h-fit rounded-2xl bg-ink p-6 text-white"><p className="text-xs font-medium text-gold">How the schedule works</p><ol className="mt-5 space-y-4 text-sm"><li><strong className="block">1. Unresolved misconception</strong><span className="mt-1 block leading-5 text-white/60">A registered error pattern still needs correction — always first.</span></li><li><strong className="block">2. Spaced checks</strong><span className="mt-1 block leading-5 text-white/60">An unassisted correct answer schedules the next check on an expanding ladder: {REVISIT_INTERVALS_DAYS.join(" → ")} days.</span></li><li><strong className="block">3. Climbing and falling</strong><span className="mt-1 block leading-5 text-white/60">A check at least 12 hours after the last one climbs a rung; cramming refreshes the clock without climbing; a miss resets the ladder.</span></li></ol><p className="mt-6 border-t border-white/15 pt-5 text-xs leading-5 text-white/55">Every date is computed from recorded timestamps in the learning record. Nothing here is a streak, an urgency score, or a guess.</p></aside>
    </div>
  </div>;
}
