import type { Metadata } from "next";
import Link from "next/link";

import MaiaCharacter from "@/components/MaiaCharacter";
import { buildDashboardSnapshot } from "@/lib/dashboard";
import { readLearnerId } from "@/lib/server/learner";

export const metadata: Metadata = { title: "Home", description: "Your courses, review queue, evidence and next learning action." };
export const dynamic = "force-dynamic";

function formatTemplate(value: string) { return value.replaceAll("-", " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }

export default async function DashboardPage() {
  const learnerId = await readLearnerId();
  const snapshot = await buildDashboardSnapshot(learnerId ?? "new-learner");
  const hasActivity = snapshot.activeLearning.length > 0;
  return <div className="mx-auto w-full max-w-[90rem] px-4 py-7 sm:px-6 lg:px-8 lg:py-9">
    <header className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between">
      <div><p className="text-sm font-medium text-lapis-dark">Your learning workspace</p><h1 className="mt-1 font-display text-3xl font-semibold tracking-[-0.035em] sm:text-4xl">Welcome back.</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-ink-soft">Continue from recorded work, review a real signal, or build from a source you trust.</p></div>
      <div className="flex items-center gap-2 text-xs"><span className="rounded-full border border-ink/10 bg-surface px-3 py-1.5 text-ink-soft">{snapshot.runtime.label}</span><span className="rounded-full border border-ink/10 bg-surface px-3 py-1.5 text-ink-soft">{snapshot.runtime.persistence === "process-local" ? "Local learning record" : "Generated work synced · lessons local"}</span></div>
    </header>

    <section className="mt-7 grid gap-4 xl:grid-cols-[minmax(0,1.35fr)_minmax(19rem,.65fr)]" aria-labelledby="next-action-title">
      <article className="relative overflow-hidden rounded-[1.6rem] border border-lapis/15 bg-surface p-5 shadow-[var(--shadow-tight)] sm:grid sm:grid-cols-[minmax(0,1fr)_9rem] sm:items-center sm:gap-5 sm:p-7">
        <div className="relative z-10"><div className="flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-correct"/><p className="text-xs font-semibold uppercase tracking-[0.08em] text-lapis-dark">Recommended next move</p></div><h2 id="next-action-title" className="mt-3 max-w-2xl text-2xl font-semibold tracking-tight sm:text-3xl">{snapshot.nextAction.title}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-ink-soft">{snapshot.nextAction.description}</p><div className="mt-5 flex flex-wrap items-center gap-3"><Link href={snapshot.nextAction.href} className="inline-flex min-h-11 items-center rounded-xl bg-lapis px-5 text-sm font-semibold text-white shadow-[0_8px_24px_rgba(43,74,203,.18)] transition hover:-translate-y-0.5 hover:bg-lapis-dark">Begin <span aria-hidden="true" className="ml-2">→</span></Link><details className="group"><summary className="cursor-pointer list-none rounded-lg px-2 py-2 text-xs font-medium text-ink-soft hover:bg-paper">Why this?</summary><p className="absolute left-5 right-5 top-full z-20 mt-2 rounded-xl border border-ink/10 bg-surface p-3 text-xs leading-5 text-ink-soft shadow-lg sm:left-auto sm:right-36 sm:w-72">{snapshot.nextAction.reason}</p></details></div></div>
        <div className="absolute -bottom-8 -right-2 opacity-20 sm:relative sm:bottom-auto sm:right-auto sm:opacity-100"><div aria-hidden="true" className="absolute inset-5 rounded-full bg-lapis-soft blur-xl"/><MaiaCharacter state="curious" className="relative h-40 w-32" title="Maia is ready to guide the next learning move"/></div>
      </article>
      <aside className="grid grid-cols-2 overflow-hidden rounded-[1.6rem] border border-ink/10 bg-surface shadow-[var(--shadow-tight)] xl:grid-cols-1">
        <div className="p-5"><div className="flex items-center justify-between"><div><p className="text-xs font-medium text-ink-soft">Review queue</p><p className="mt-2 text-3xl font-semibold tabular-nums">{snapshot.reviewQueue.length}</p></div><span className="grid h-10 w-10 place-items-center rounded-xl bg-gold-soft text-lg" aria-hidden="true">↻</span></div><p className="mt-3 hidden text-sm leading-6 text-ink-soft sm:block">{snapshot.reviewQueue.length ? "Ranked from recorded learning signals." : "Items appear only after a real signal."}</p></div>
        <div className="border-l border-ink/8 p-5 xl:border-l-0 xl:border-t"><p className="text-xs font-medium text-ink-soft">Evidence signals</p><p className="mt-2 text-3xl font-semibold tabular-nums">{snapshot.evidence.length}</p><Link href="/progress" className="mt-3 inline-flex min-h-10 items-center text-sm font-semibold text-lapis-dark">Inspect record <span aria-hidden="true" className="ml-1">→</span></Link></div>
      </aside>
    </section>

    <section aria-label="Museion learning protocol" tabIndex={0} className="mt-4 overflow-x-auto rounded-2xl border border-ink/8 bg-surface px-4 py-3 shadow-[var(--shadow-tight)] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-lapis">
      <ol className="grid min-w-[42rem] grid-cols-5 gap-2">{[["01","Observe","Source"],["02","Predict","Commit"],["03","Test","Check"],["04","Revise","With Maia"],["05","Transfer","Unassisted"]].map(([number,title,detail], index) => <li key={title} className="relative flex items-center gap-3 px-2"><span className={`grid h-8 w-8 shrink-0 place-items-center rounded-full text-[0.65rem] font-semibold ${index === 0 ? "bg-lapis text-white" : "bg-paper text-ink-soft"}`}>{number}</span><span><span className="block text-xs font-semibold">{title}</span><span className="block text-[0.66rem] text-ink-soft">{detail}</span></span>{index < 4 && <span aria-hidden="true" className="absolute -right-1 h-px w-3 bg-ink/15"/>}</li>)}</ol>
    </section>

    <div className="mt-7 grid gap-6 xl:grid-cols-[minmax(0,1.35fr)_minmax(20rem,.65fr)]">
      <div className="space-y-6">
        <section aria-labelledby="active-title"><div className="mb-3 flex items-end justify-between"><div><p className="text-xs font-medium text-ink-soft">Courses</p><h2 id="active-title" className="mt-1 text-xl font-semibold">Continue learning</h2></div><Link href="/library" className="text-sm font-medium text-lapis-dark">View library</Link></div>
          {hasActivity ? <div className="grid gap-3 sm:grid-cols-2">{snapshot.activeLearning.map((item) => <Link key={item.id} href={item.href} className="group rounded-2xl border border-ink/10 bg-surface p-5 shadow-[var(--shadow-tight)] transition hover:-translate-y-0.5 hover:border-lapis/30"><div className="flex items-center justify-between gap-3"><span className="rounded-full bg-paper px-2.5 py-1 text-[0.68rem] font-medium text-ink-soft">{item.kind === "generated" ? "From your source" : "Museion lesson"}</span><span className="text-xs tabular-nums text-ink-soft">{Math.round(item.progress * 100)}%</span></div><h3 className="mt-4 font-semibold group-hover:text-lapis-dark">{item.title}</h3><p className="mt-1.5 text-sm text-ink-soft">{item.detail}</p><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-ink/8"><div className="h-full rounded-full bg-lapis" style={{ width: `${Math.max(4, item.progress * 100)}%` }} /></div></Link>)}</div> : <div className="rounded-2xl border border-dashed border-ink/15 bg-surface p-6"><p className="font-semibold">Your workspace is ready.</p><p className="mt-2 text-sm leading-6 text-ink-soft">Start an interactive foundation or create a course from one source.</p><div className="mt-4 flex flex-wrap gap-3"><Link href="/library" className="rounded-lg bg-ink px-4 py-2.5 text-sm font-semibold text-white">Browse lessons</Link><Link href="/create" className="rounded-lg border border-ink/15 px-4 py-2.5 text-sm font-semibold">Create a course</Link></div></div>}
        </section>

        <section aria-labelledby="evidence-title" className="rounded-2xl border border-ink/10 bg-surface p-5 shadow-[var(--shadow-tight)] sm:p-6"><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-medium text-ink-soft">Understanding evidence</p><h2 id="evidence-title" className="mt-1 text-xl font-semibold">What the record supports</h2></div><Link href="/progress" className="text-sm font-medium text-lapis-dark">See evidence</Link></div>
          {snapshot.evidence.length ? <div className="mt-5 grid gap-x-6 gap-y-1 sm:grid-cols-2">{snapshot.evidence.slice(0,6).map((item) => <div key={`${item.concept}:${item.state}`} className="flex items-center justify-between border-t border-ink/8 py-3"><div><p className="text-sm font-medium">{item.concept}</p><p className="mt-0.5 text-xs text-ink-soft">{item.state === "observed-guided" ? "Observed in guided work" : item.state === "hint-free-practice" ? "Hint-free practice completed" : "Immediate near transfer"}</p></div><span className={`rounded-full px-2.5 py-1 text-xs font-medium ${item.result === "incorrect" || item.result === "developing" ? "bg-gold-soft text-ink" : "bg-correct-soft text-correct"}`}>{item.result}</span></div>)}</div> : <p className="mt-4 text-sm leading-6 text-ink-soft">No concept evidence yet. A checked response will create the first record.</p>}
        </section>
      </div>

      <aside className="space-y-6">
        <section className="rounded-2xl border border-ink/10 bg-surface p-5 shadow-[var(--shadow-tight)]" aria-labelledby="misconceptions-title"><div className="flex items-center justify-between"><h2 id="misconceptions-title" className="font-semibold">Recent misconceptions</h2><span className="text-xs text-ink-soft">{snapshot.misconceptions.length}</span></div>{snapshot.misconceptions.length ? <div className="mt-3 divide-y divide-ink/8">{snapshot.misconceptions.slice(0,3).map((item) => <Link key={`${item.id}:${item.observedAt}`} href={item.href} className="block py-3"><p className="text-xs font-medium text-lapis-dark">{item.concept}</p><p className="mt-1 line-clamp-2 text-sm leading-5 text-ink">{item.label}</p><p className="mt-1 text-xs text-ink-soft">{item.status === "corrected-in-session" ? "Corrected during the session; worth rechecking" : "Not yet resolved"}</p></Link>)}</div> : <p className="mt-3 text-sm leading-6 text-ink-soft">No registered misconception has been observed.</p>}<Link href="/review" className="mt-3 inline-flex text-sm font-semibold text-lapis-dark">Open misconception lab</Link></section>

        <section className="rounded-2xl border border-ink/10 bg-surface p-5 shadow-[var(--shadow-tight)]" aria-labelledby="sources-title"><div className="flex items-center justify-between"><h2 id="sources-title" className="font-semibold">Recent sources</h2><Link href="/create" className="text-xs font-medium text-lapis-dark">Add source</Link></div>{snapshot.recentSources.length ? <div className="mt-3 divide-y divide-ink/8">{snapshot.recentSources.map((source) => <Link key={source.id} href={source.href} className="block py-3"><p className="truncate text-sm font-medium">{source.title}</p><p className="mt-1 text-xs text-ink-soft">{source.pages} {source.pages === 1 ? "page" : "pages"} · {formatTemplate(source.templateId)}</p></Link>)}</div> : <p className="mt-3 text-sm leading-6 text-ink-soft">Compiled sources will appear here for their retention window.</p>}</section>
      </aside>
    </div>
    <p className="mt-7 border-t border-ink/10 pt-4 text-xs leading-5 text-ink-soft">{snapshot.limitations[0]} <Link href="/progress" className="font-medium text-lapis-dark">Read the evidence boundary.</Link></p>
  </div>;
}
